#!/bin/bash
# Usa el directorio de neovim SOLO si es diferente del directorio actual
if [[ -n "$TMUX_NVIM_CWD" && "$TMUX_NVIM_CWD" != "$PWD" ]]; then
    TARGET_DIR="$TMUX_NVIM_CWD"
else
    TARGET_DIR="$PWD"
fi
cd "$TARGET_DIR" || exit 1
exec direnv exec "$PWD" /Users/jmurphy/.opencode/bin/opencode "$@"
